version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgersql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "python -m main"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - postgres

volumes:
  pgdata: